[package]
name = "PhasSaveEditor"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
aes = "0.7"
block-modes = "0.8"
block-padding = "0.2"
pbkdf2 = "0.12"
sha1 = "0.10"
regex = "1"
serde_json = "1"
serde = { version = "1", features = ["derive"] }